### ISSUE TITLE
Parallel execution across groups

### ISSUE THREAD

**Issue by nizacegodk** [cego/gitte#113]
Running a single action across all groups on a single project is very slow, since jobs are executed sequentially and not in parallel. Especially if the project has dependencies.

``gitte run my-action '*' my-project``

**Comment by firecow** [comment]
I thought all actions was run in parallel. You sure the projects you are waiting for, isn't `need:` 'ed ? @nizacegodk

**Comment by nizacegodk** [comment]
@firecow actions are run in parallel. But groups are run sequentially. And since I only want to run a single action in each group. Those actions will be run sequentially.
