### ISSUE TITLE
'gitops' output on non-existing branch

### ISSUE THREAD

**Issue by atli-c** [cego/gitte#139]
Command `gitte gitops` misleading output when origin branch does not exist

Misleading outputs:
> example-branch-name conflicts with origin/example-branch-name in ~/path/to/clone
> example-branch-name is 2 commits behind master in ~/path/to/clone

Expected output:
> example-branch-name upstream origin/example-branch-name doesn't exist in ~/path/to/clone
> example-branch-name is 2 commits behind master in ~/path/to/clone

**Comment by atc-cegodk** [comment]
My machine: macOS Monterey 12.6 (Intel CPU)  
`git --version`
> git version 2.37.0 (Apple Git-136)

**Comment by atc-cegodk** [comment]
[src/gitops.ts:29](https://github.com/cego/gitte/blob/40d5a56c2396bc5883d1e11b5f9dedb51cdb502b/src/gitops.ts#L29) uses `.startsWith()`. This might not always work.

`git pull --ff-only` some times outputs:
> There is no tracking information for the current branch.
> Please specify which branch …

`git pull --ff-only` some other times it outputs:  
> remote: Enumerating objects: 13, done.
> remote: Counting objects: 100% (13/13), done.
> remote: Compressing objects: 100% (12/12), done.
> remote: Total 13 (delta 0), reused 0 (delta 0), pack-reused 0
> Unpacking objects: 100% (13/13), 5.66 KiB | 579.00 KiB/s, done.
> From server:repo/redacted
>    4c7c4c150d8..415e6393908  master     -> origin/master
> There is no tracking information for the current branch.
> Please specify which branch you want to merge with.

**Comment by LauJosefsen** [comment]
Should be solved as recent gitte version
