### ISSUE TITLE
Make "run" command default

### ISSUE THREAD

**Issue by nizacegodk** [cego/gitte#77]
Currenctly I have to run `git-local-devops run up sn` but since `up` is a custom defined action, I would prefer to ommit the `run` part of the command.

So `git-local-devops up sn` is equvivalent with `git-local-devops run up sn` by making `run` the default command.

**Comment by LauJosefsen** [comment]
Would also solve potential confusion between run and actions.

**Comment by firecow** [comment]
When implementing this behavior remember to guard against having "action names" that clashes with our commands like "gitops", "startup", "actions", "list", "validate" and "help".
Future command additions could conflict with already existing "action names" in people's configs

**Comment by LauJosefsen** [comment]
What should expected behavior be in that case? Fail fast?

**Comment by LauJosefsen** [comment]
Would it be worth considering nested cmd-dir?

Since `run` is the main command, then have some structure like
`git-local-devops up project` - runs up actions in group project
and
`git-local-devops run <gitops|startup|list|validate|...>` for everything else, and just have run (can be another word than run) reserved?

**Comment by firecow** [comment]
Actions cannot be called `do` if that scenario.
But its better than colliding with every word in every language :laughing:

**Comment by LauJosefsen** [comment]
We will wait and see if more people share this opinion, but will keep the current command structure for now.

**Comment by LauJosefsen** [comment]
Future flexibility is preferred for now rather than saving 3 keypresses per action. Might reopen later if situation changes.
